import parentRoute from '../route.js';

/** AirLib managed */
const route = parentRoute.route('/components');
const indexRoute = route.route('/');
const badgeRoute = route.route('/badge');
const buttonGroupRoute = route.route('/button-group');
const buttonRoute = route.route('/button');
const cardRoute = route.route('/card');
const checkboxRoute = route.route('/checkbox');
const chipRoute = route.route('/chip');
const colorPickerRoute = route.route('/color-picker');
const datePickerRoute = route.route('/date-picker');
const dialogRoute = route.route('/dialog');
const dividerRoute = route.route('/divider');
const fabMenuRoute = route.route('/fab-menu');
const fabRoute = route.route('/fab');
const iconButtonRoute = route.route('/icon-button');
const linkRoute = route.route('/link');
const listRoute = route.route('/list');
const menuRoute = route.route('/menu');
const progressRoute = route.route('/progress');
const radioRoute = route.route('/radio');
const rippleRoute = route.route('/ripple');
const searchBarRoute = route.route('/search-bar');
const segmentedButtonRoute = route.route('/segmented-button');
const selectRoute = route.route('/select');
const sliderRoute = route.route('/slider');
const snackbarRoute = route.route('/snackbar');
const splitButtonRoute = route.route('/split-button');
const switchRoute = route.route('/switch');
const tableRoute = route.route('/table');
const textFieldRoute = route.route('/text-field');
const timePickerRoute = route.route('/time-picker');
const tooltipRoute = route.route('/tooltip');
/** AirLib managed */

export const componentsRoute = route;
export const componentsIndexRoute = indexRoute;
export const componentsBadgeRoute = badgeRoute;
export const componentsButtonGroupRoute = buttonGroupRoute;
export const componentsButtonRoute = buttonRoute;
export const componentsCardRoute = cardRoute;
export const componentsCheckboxRoute = checkboxRoute;
export const componentsChipRoute = chipRoute;
export const componentsColorPickerRoute = colorPickerRoute;
export const componentsDatePickerRoute = datePickerRoute;
export const componentsDialogRoute = dialogRoute;
export const componentsDividerRoute = dividerRoute;
export const componentsFabMenuRoute = fabMenuRoute;
export const componentsFabRoute = fabRoute;
export const componentsIconButtonRoute = iconButtonRoute;
export const componentsLinkRoute = linkRoute;
export const componentsListRoute = listRoute;
export const componentsMenuRoute = menuRoute;
export const componentsProgressRoute = progressRoute;
export const componentsRadioRoute = radioRoute;
export const componentsRippleRoute = rippleRoute;
export const componentsSearchBarRoute = searchBarRoute;
export const componentsSegmentedButtonRoute = segmentedButtonRoute;
export const componentsSelectRoute = selectRoute;
export const componentsSliderRoute = sliderRoute;
export const componentsSnackbarRoute = snackbarRoute;
export const componentsSplitButtonRoute = splitButtonRoute;
export const componentsSwitchRoute = switchRoute;
export const componentsTableRoute = tableRoute;
export const componentsTextFieldRoute = textFieldRoute;
export const componentsTimePickerRoute = timePickerRoute;
export const componentsTooltipRoute = tooltipRoute;

export default componentsRoute;
