name = "anchor-next"
main = ".open-next/worker.js"
compatibility_date = "2025-08-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
VITE_ROOT_URL="https://anchor.mahdaen.name"
VITE_WORKER_BUILD=true
VITE_WORKER_BUILD_URL="https://anchor.mahdaen.name/docs/"
