import { getContext, setContext } from '../scope/index.js';

let lastTimestamp = 0;
let sequence = 0;

export function shortId(): string {
  const timestamp = Date.now();

  if (timestamp === lastTimestamp) {
    sequence++;
  } else {
    sequence = 0;
  }
  lastTimestamp = timestamp;

  const timestampPart = timestamp.toString(36);
  const sequencePart = sequence.toString(36).padStart(3, '0');
  const randomPart = Math.random().toString(36).substring(2, 6);

  return `${timestampPart}${sequencePart}${randomPart}`;
}

/**
 * A function that generates a random UUID string.
 *
 * @returns A UUID v4 string in the format xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx
 */
export type UUIDProvider = () => string;

/**
 * Generates a random UUID v4 string using a simple algorithm.
 *
 * @returns A UUID v4 string in the format xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx
 */
function simpleId(): string {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

/**
 * Default UUID provider that attempts to use the crypto API if available,
 * otherwise falls back to a simpler implementation.
 *
 * @returns A UUID v4 string
 */
function defaultUUIDProvider() {
  if (typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID();
  }

  return simpleId();
}

/**
 * The currently active UUID provider function.
 */
let uuidProvider: UUIDProvider = defaultUUIDProvider;

/**
 * Generates a new UUID using the currently configured provider.
 *
 * @returns A UUID string generated by the current provider
 */
export function uuid(): string {
  return (uuidProvider ?? defaultUUIDProvider)();
}

/**
 * Sets a custom UUID provider function to be used by the uuid() function.
 *
 * @param provider - A function that returns a UUID string when called
 */
export function setUUIDProvider(provider: UUIDProvider) {
  uuidProvider = provider;
}

/**
 * Creates a unique index within the current scope.

 * @param name - The name of the unique index.
 * @param scoped - Use the nearest index store.
 * @returns The next unique index value.
 */
export const uIndex = (name: symbol, scoped?: boolean) => {
  if (scoped) {
    let store = getContext<{ value: number }>(name);
    if (!store) {
      store = { value: 0 };
      setContext(name, store);
    }
    store.value += 1;
    return store.value;
  }

  let value = getContext<number>(name);

  if (typeof value !== 'number') {
    value = 0;
    setContext(name, value);
  }

  value += 1;
  setContext(name, value);
  return value;
};
