/**
 * A function that generates a random UUID string.
 *
 * @returns A UUID v4 string in the format xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx
 */
export type UUIDProvider = () => string;

/**
 * Generates a random UUID v4 string using a simple algorithm.
 *
 * @returns A UUID v4 string in the format xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx
 */
function simpleId(): string {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
}

/**
 * Default UUID provider that attempts to use the crypto API if available,
 * otherwise falls back to a simpler implementation.
 *
 * @returns A UUID v4 string
 */
function defaultUUIDProvider() {
  if (typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID();
  }

  return simpleId();
}

/**
 * The currently active UUID provider function.
 */
let uuidProvider: UUIDProvider = defaultUUIDProvider;

/**
 * Generates a new UUID using the currently configured provider.
 *
 * @returns A UUID string generated by the current provider
 */
export function uuid(): string {
  return (uuidProvider ?? defaultUUIDProvider)();
}

/**
 * Sets a custom UUID provider function to be used by the uuid() function.
 *
 * @param provider - A function that returns a UUID string when called
 */
export function setUUIDProvider(provider: UUIDProvider) {
  uuidProvider = provider;
}
